### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by DockerBB** [xxlya/Fed_ABIDE#1]
How to generate the following data? I don't seem to find how to generate these data in the data processing code.
![](https://ftp.bmp.ovh/imgs/2021/01/aed8b4ecf2ccad94.png)

**Comment by Yufeng98** [comment]
Hi! Thanks for your message. Sorry about the late reply.
Have you run the single.py? in line 41 and 58, it save the split id in ${site}_sub_overlap.h5 files. This step implements a 5-folder cross validation in order to split training and test dataset, and also comfirms that the truncated subject will not fall into both training and test sets.
Please feel free to let me if it still does not work.

**Comment by DockerBB** [comment]
Ok, thank you for the explain. 👍
